# This is a basic workflow to help you get started with Actions

name: timer

# Controls when the workflow will run
on:
  schedule:
  - cron: "30 20 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'dada'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      # Runs a single command using the runners shell
      - name: install imagemagick
        run: sudo apt install -y imagemagick
        
      # Runs a set of commands using the runners shell
      - name: playlist automation
        run: bash -x automator.sh
        env:
          NETEASE_MUSIC_API: ${{ secrets.NETEASE_MUSIC_API }}
          NETEASE_MUSIC_USERNAME: ${{ secrets.NETEASE_MUSIC_USERNAME }}
          NETEASE_MUSIC_PASSWORD: ${{ secrets.NETEASE_MUSIC_PASSWORD }}
          NETEASE_MUSIC_PLAYLIST_ID: ${{ secrets.NETEASE_MUSIC_PLAYLIST_ID }}


      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playlists
